train:
  num_samples: 1024
  n_epochs: 1000000
  batch_size: 1
  accumulation_steps: 64
  sample_rate: 24000
  learning_rate: 0.0001
  bos_token: 0
  weight_decay: 1e-4
  resume_from_checkpoint: "/home/infres/lasri-22/tts/outputs/2025-10-26/20-32-57/runs/tts_20251026_203257/checkpoints/model_epoch_200.pt"  # null or path to checkpoint

model:
  text_embed_dim: 512
  text_num_layers: 2
  num_decoder_layers: 2

rvq:
  n_bins: 1024
  n_quantizers: 32

dataset:
  root_dir: "./datasets/cmu_us_awb_arctic"
  wav_dir: "wav"
  text_file: "etc/txt.done.data"

logging:
  log_dir: "runs"
  save_every: 5000
